#! /usr/bin/python
# -*- coding:utf-8 -*-

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
print 'set bcm'
#第3号针，GPIO2
GPIO.setup(2,GPIO.OUT,initial=GPIO.LOW)
print 'set 2 output low'
#第5号针，GPIO3
GPIO.setup(3,GPIO.IN)
print 'set 3 in'

def checkdist():
    print 'Function start...'
    #发出触发信号
    GPIO.output(2,GPIO.HIGH)
    print 'output 2 high'
    #保持10us以上（我选择15us）
    time.sleep(0.000015)
    print 'sleep 15us'
    GPIO.output(2,GPIO.LOW)
    print 'output 2 low'
    while not GPIO.input(3):
        pass
    print 'pass input3'
    #发现高电平时开时计时
    t1 = time.time()
    print t1
    while GPIO.input(3):
        pass
    print 'pass input 3 again'
    #高电平结束停止计时
    t2 = time.time()
    print t2
    #返回距离，单位为米
    return (t2-t1)*340/2


print 'Sleep 2 sceonds now...'
time.sleep(2)

print 'Calculating distance...'
try:
    while True:
        print 'Calculating......'
        #print 'Distance: %0.2f m' %checkdist()
        dis = checkdist()
        print dis
        time.sleep(0.5)
except: #KeyboardInterrupt:
    GPIO.cleanup()
    print 'Exception...'
